### ISSUE TITLE
Type: string keeps being translated to Sequlize.TEXT instead of .STRING

### ISSUE THREAD

**Issue by murbanowicz** [feathers-plus/cli#15]
### Steps to reproduce

1. Create Schema with empty {} or type: 'string'
2. Regenerate sequalize models

### Expected behavior
Properties with 'STRING' should have .STRING in Sequalize models.

### Actual behavior
All are TEXT 
### System configuration
All the latest.

**Comment by eddyystop** [comment]
The conversion from JSON-schema to a Sequelize model is done using Sequelizer.fromJsonSchema. fromJsonSchema is what is converting `{ type: 'string' }` to `{ type: DataTypes.TEXT }`.

Let me speak to some people who have been using cli+ with Sequelize.

**Comment by eddyystop** [comment]
The conversion is done by `require('sequelizer').fromJsonSchema`.

Strings with a `maxLength` prop of less than 256 are converted to STRING. Otherwise they are converted to TEXT.

So you'll have to specify a `maxLength`.

You should be doing this anyway if you want to use the data faker just introduced (in beta): https://generator.feathers-plus.com/get-started/#generate-fakes
